spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.main.allow-bean-definition-overriding=true

# debug MongoDB
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.mongodb.driver=DEBUG

#Porta Da Aplicação
server.port=8080
#Configuração Do Banco H2
spring.datasource.url=jdbc:h2:mem:cruddmongo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
#JPA (para persitência)
spring.jpa.hibernate.dll-auto=update
#console do h2 habilitado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
